site_name: ROBLOX Reverse-Engineering
repo_name: ROBLOX Reverse-Engineering/RRE-Site
repo_url: https://github.com/ROBLOX-Reverse-Engineering/RRE-Site
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/iTunesArtwork@2xNoBG.png
  favicon: assets/iTunesArtwork@2xNoBG.png
  icon:
    edit: material/file-edit-outline
    admonition:
      bug: material/alert
  palette: 
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
nav:
    - Home: 'index.md'
    - What is Reversing?: 'AboutReversing.md'
    - Client Features:
      - JoinScripts: 'Client Features/JoinScripts.md'
    - Client Security:
      - What are signatures?: 'Client Security/Signatures.md'
    - Common Issues:
      - Issue 1: 'Common Issues/test.md'
      - Issue 2: 'Common Issues/test2.md'
    - Extras:
      - Generating a public/private key: 'Extras/KeyGeneration.md'
      - Honorable Users:
        - Brent: "Honorable Users/Brent.md"
extra:
  generator: false
extra_css:
  - assets/Extra.css
plugins:
  - search
  - exclude-search:
      exclude: 
        - hidden/*
markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: We're not affiliated, associated, authorized, or endorsed by ROBLOX Corporation in any way, shape, or form.